# Generated by Django 5.1.6 on 2025-02-11 10:46

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('collage_id', models.AutoField(primary_key=True, serialize=False)),
                ('collage_name', models.CharField(max_length=100)),
                ('collage_addgress', models.CharField(max_length=100)),
                ('collage_email', models.CharField(max_length=50)),
                ('collage_type', models.CharField(choices=[('Engineering', 'Engineering'), ('Medical', 'Medical'), ('Arts', 'Arts'), ('Business', 'Business'), ('MBA', 'MBA')], max_length=50)),
                ('collage_phone', models.CharField(max_length=10)),
                ('collage_about', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('timeDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=50)),
                ('faculty_email', models.EmailField(max_length=50)),
                ('faculty_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=10, region=None)),
                ('faculty_type', models.CharField(choices=[('Cleaning Staff', 'Cleaning Staff'), ('Professor', 'Professor'), ('Accountant Staff', 'Accountant Staff'), ('Laboratory Staff', 'Laboratory Staff')], max_length=50)),
                ('faculty_about', models.TextField()),
                ('faculty_exprience', models.IntegerField()),
                ('faculty_collage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.collage')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('student_email', models.EmailField(max_length=50)),
                ('student_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=10, region=None)),
                ('student_degree', models.CharField(choices=[('Graduation', 'Graduation'), ('Post Graduation', 'Post Graduation'), ('PHD', 'PHD')], max_length=50)),
                ('student_degree_specific', models.CharField(choices=[('BTech', 'BTech'), ('BE', 'BE'), ('MBBS', 'MBBS'), ('MD', 'MD'), ('BCom', 'BCom'), ('BSc', 'BBc')], max_length=50)),
                ('student_addmission_date', models.DateTimeField(auto_now=True)),
                ('student_about', models.TextField()),
                ('student_collage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.collage')),
            ],
        ),
    ]
